const imgtime=(ms)=> new Promise((resolve) => setTimeout(resolve,ms));
async function imgshift(){
   document.body.style.background = "url('images/gojo.jpg') center/cover no-repeat";
    await imgtime(60000);
    document.body.style.opacity=1;
    await imgtime(10);
    document.body.style.opacity=0.95;
    await imgtime(10);
    document.body.style.opacity=0.9;
    await imgtime(10);
    document.body.style.opacity=0.85;
    await imgtime(10);
  document.body.style.opacity=0.8;
    await imgtime(10);
    document.body.style.opacity=0.75;
    await imgtime(10);
    document.body.style.opacity=0.7;
    await imgtime(10);
    document.body.style.opacity=0.65;
    await imgtime(10);
      document.body.style.opacity=0.6;
    await imgtime(10);
    document.body.style.opacity=0.55;
    await imgtime(10);
    document.body.style.opacity=0.5;
    await imgtime(10);
    document.body.style.opacity=0.45;
    await imgtime(10);
      document.body.style.opacity=0.4;
    await imgtime(10);
    document.body.style.opacity=0.35;
    await imgtime(10);
    document.body.style.opacity=0.3;
    await imgtime(10);
    document.body.style.opacity=0.25;
    await imgtime(10);
      document.body.style.opacity=0.2;
    await imgtime(10);
    document.body.style.opacity=0.15;
    await imgtime(10);
    document.body.style.opacity=0.1;
    await imgtime(10);
    document.body.style.opacity=0.05;
    await imgtime(10);
     document.body.style.opacity=0;
     await imgtime(10);
     document.body.style.opacity=1;
     document.body.style.background = "url('images/choso.jpg') center/cover no-repeat";
    await imgtime(60000);
    document.body.style.opacity=0.95;
    await imgtime(10);
    document.body.style.opacity=0.9;
    await imgtime(10);
    document.body.style.opacity=0.85;
    await imgtime(10);
  document.body.style.opacity=0.8;
    await imgtime(10);
    document.body.style.opacity=0.75;
    await imgtime(10);
    document.body.style.opacity=0.7;
    await imgtime(10);
    document.body.style.opacity=0.65;
    await imgtime(10);
      document.body.style.opacity=0.6;
    await imgtime(10);
    document.body.style.opacity=0.55;
    await imgtime(10);
    document.body.style.opacity=0.5;
    await imgtime(10);
    document.body.style.opacity=0.45;
    await imgtime(10);
      document.body.style.opacity=0.4;
    await imgtime(10);
    document.body.style.opacity=0.35;
    await imgtime(10);
    document.body.style.opacity=0.3;
    await imgtime(10);
    document.body.style.opacity=0.25;
    await imgtime(10);
      document.body.style.opacity=0.2;
    await imgtime(10);
    document.body.style.opacity=0.15;
    await imgtime(10);
    document.body.style.opacity=0.1;
    await imgtime(10);
    document.body.style.opacity=0.05;
    await imgtime(10);
    document.body.style.opacity=0;
    await imgtime(10);
}
imgshift();
requestAnimationFrame(imgshift);